/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FunctionalityRouteImport } from './routes/functionality'
import { Route as IndexRouteImport } from './routes/index'

const FunctionalityRoute = FunctionalityRouteImport.update({
  id: '/functionality',
  path: '/functionality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/functionality': typeof FunctionalityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/functionality': typeof FunctionalityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/functionality': typeof FunctionalityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/functionality'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/functionality'
  id: '__root__' | '/' | '/functionality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FunctionalityRoute: typeof FunctionalityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/functionality': {
      id: '/functionality'
      path: '/functionality'
      fullPath: '/functionality'
      preLoaderRoute: typeof FunctionalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FunctionalityRoute: FunctionalityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
